version: 1.0
provider:
  name: openfaas
  gateway: https://faasd.alexfranz.com
functions:
  faasd-demo:
    lang: python3-fastapi
    handler: ./faasd-demo
    image: ghcr.io/alfranz/faasd-demo:latest

